### PR TITLE
Added skeleton for the procedural Sub building application

### PR DESCRIPTION
**Pull request by ShannonHolgate**

### CODE REVIEW

**Comment by John-Doherty01** [comment]
#VeganAwarness

**Comment by bmckillop** [comment]
Thats some good sub building!

**Review by lburns660 — APPROVED** [review]
sweet to the beat

**Comment by calumforster** [comment]
Lovely.

**Review by bmckillop — APPROVED** [review]

**Comment by mmartin660** [comment]
cool

**Review by calumforster — APPROVED** [review]
B E A UUUTIFUL

**Pull request merged**
